# permissions for end users to view enoexecevents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: enoexecevent-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multiarch-tuning-operator
    app.kubernetes.io/part-of: multiarch-tuning-operator
    app.kubernetes.io/managed-by: kustomize
  name: enoexecevent-viewer-role
rules:
- apiGroups:
  - multiarch.openshift.io
  resources:
  - enoexecevents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multiarch.openshift.io
  resources:
  - enoexecevents/status
  verbs:
  - get
