---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  - serviceaccounts/status
  - services/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - pod-placement-mutating-webhook-configuration
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multiarch.openshift.io
  resources:
  - clusterpodplacementconfigs
  - enoexecevents
  - podplacementconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multiarch.openshift.io
  resources:
  - clusterpodplacementconfigs/finalizers
  - enoexecevents/finalizers
  - podplacementconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - multiarch.openshift.io
  resources:
  - clusterpodplacementconfigs/status
  - enoexecevents/status
  - podplacementconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - enoexec-event-daemon
  - enoexec-event-handler-controller
  - pod-placement-controller
  - pod-placement-web-hook
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings/finalizers
  - clusterroles/finalizers
  - rolebindings/finalizers
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings/status
  - clusterroles/status
  - rolebindings/status
  - roles/status
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - enoexec-event-daemon
  - enoexec-event-handler-controller
  - pod-placement-controller
  resources:
  - rolebindings
  - roles
  verbs:
  - delete
  - get
  - patch
  - update
