//go:build !ignore_autogenerated

/*
Copyright 2023 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package plugins

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasePlugin) DeepCopyInto(out *BasePlugin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasePlugin.
func (in *BasePlugin) DeepCopy() *BasePlugin {
	if in == nil {
		return nil
	}
	out := new(BasePlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecFormatErrorMonitor) DeepCopyInto(out *ExecFormatErrorMonitor) {
	*out = *in
	out.BasePlugin = in.BasePlugin
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecFormatErrorMonitor.
func (in *ExecFormatErrorMonitor) DeepCopy() *ExecFormatErrorMonitor {
	if in == nil {
		return nil
	}
	out := new(ExecFormatErrorMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAffinityScoring) DeepCopyInto(out *NodeAffinityScoring) {
	*out = *in
	out.BasePlugin = in.BasePlugin
	if in.Platforms != nil {
		in, out := &in.Platforms, &out.Platforms
		*out = make([]NodeAffinityScoringPlatformTerm, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAffinityScoring.
func (in *NodeAffinityScoring) DeepCopy() *NodeAffinityScoring {
	if in == nil {
		return nil
	}
	out := new(NodeAffinityScoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAffinityScoringPlatformTerm) DeepCopyInto(out *NodeAffinityScoringPlatformTerm) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAffinityScoringPlatformTerm.
func (in *NodeAffinityScoringPlatformTerm) DeepCopy() *NodeAffinityScoringPlatformTerm {
	if in == nil {
		return nil
	}
	out := new(NodeAffinityScoringPlatformTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Plugins) DeepCopyInto(out *Plugins) {
	*out = *in
	if in.NodeAffinityScoring != nil {
		in, out := &in.NodeAffinityScoring, &out.NodeAffinityScoring
		*out = new(NodeAffinityScoring)
		(*in).DeepCopyInto(*out)
	}
	if in.ExecFormatErrorMonitor != nil {
		in, out := &in.ExecFormatErrorMonitor, &out.ExecFormatErrorMonitor
		*out = new(ExecFormatErrorMonitor)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Plugins.
func (in *Plugins) DeepCopy() *Plugins {
	if in == nil {
		return nil
	}
	out := new(Plugins)
	in.DeepCopyInto(out)
	return out
}
