apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/multiarch-tuning-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "fbc"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fbc-v4-19
    appstudio.openshift.io/component: fbc-v4-19
    pipelines.appstudio.openshift.io/type: build
  name: fbc-v4-19-on-pull-request
  namespace: multiarch-tuning-ope-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile
  - name: git-url
    value: '{{source_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/fbc-v4-19/fbc-v4-19:on-pr-{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: hermetic
    value: "true"
  - name: BUILD_ARGS
    value:
      - 'BASE_IMAGE=registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.19'
      - 'OCP_VERSION=fbc-v4-19'
  taskRunTemplate: {}
  pipelineRef:
    resolver: bundles
    params:
      - name: name
        value: fbc-builder
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:devel@sha256:828549e02575922b985173b8b77e82de87f746e60c743984eae524fbf7686162
      - name: kind
        value: pipeline
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
