kind: ImageDigestMirrorSet
apiVersion: operator.openshift.io/v1alpha1
metadata:
  name: multiarch-tuning-operator-fbc-staging-index
spec:
  imageDigestMirrors:
    - source: registry.redhat.io/multiarch-tuning/multiarch-tuning-operator-bundle
      mirrors:
        - quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator-1-0/multiarch-tuning-operator-bundle-1-0
        - quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator/multiarch-tuning-operator-bundle
    - source: registry.redhat.io/multiarch-tuning/multiarch-tuning-rhel9-operator
      mirrors:
        - quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator-1-0/multiarch-tuning-operator-1-0
        - quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator/multiarch-tuning-operator
