kind: Pipeline
apiVersion: tekton.dev/v1
metadata:
  name: integration-and-unit-tests
  namespace: multiarch-tuning-ope-tenant
spec:
  params: [ ]
  tasks:
    - name: clone-and-test
      taskSpec:
        volumes:
          - name: source
            emptyDir: { }
        steps:
          - image: brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23
            env:
              - name: URL
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/source-repo-url']
              - name: REVISION
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/sha']
            computeResources:
              limits:
                cpu: 8
                memory: 4Gi
              requests:
                cpu: 500m
                memory: 1Gi
            volumeMounts:
              - name: source
                mountPath: /workspace
            script: |
              #!/bin/bash
              set -exuo pipefail
              if [ -z "$URL" ] || [ -z "$REVISION" ]; then
                echo "URL and REVISION must be set"
                exit 1
              fi
              echo "Initializing the env vars"
              echo "URL: $URL"
              echo "REVISION: $REVISION"
              mkdir /workspace/source
              cd /workspace/source
              git init
              git remote add origin $URL
              git fetch origin $REVISION
              git checkout FETCH_HEAD
              make unit NO_DOCKER=1
              exit $? # exit with the status of the tests
