apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/multiarch-tuning-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && target_branch == "v1.0" && (".tekton/***".pathChanged() || "apis/***".pathChanged() || "controllers/***".pathChanged() || "pkg/***".pathChanged() || "test/***".pathChanged() || "konflux.Dockerfile".pathChanged() || "go.mod".pathChanged() || "main.go".pathChanged() || "go.sum".pathChanged() || "trigger-konflux-builds.txt".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: multiarch-tuning-operator-v1-0
    appstudio.openshift.io/component: multiarch-tuning-operator-v1-0
    pipelines.appstudio.openshift.io/type: build
  name: multiarch-tuning-operator-v1-0-on-pull-request
  namespace: multiarch-tuning-ope-tenant
spec:
  params:
    - name: dockerfile
      value: konflux.Dockerfile
      # TODO: change to Dockerfile when https://issues.redhat.com/browse/KONFLUX-2361
    - name: git-url
      value: '{{source_url}}'
    - name: image-expires-after
      value: 5d
    - name: output-image
      value: quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator-v1-0/multiarch-tuning-operator-v1-0:on-pr-{{revision}}
    - name: path-context
      value: .
    - name: revision
      value: '{{revision}}'
    - name: build-platforms
      value:
        - linux/amd64
        - linux/arm64
        - linux/ppc64le
        - linux/s390x
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: '{"packages": [{"type": "gomod"}], "flags": ["gomod-vendor-check"]}'
    - name: build-source-image
      value: "true"
  pipelineRef:
    resolver: bundles
    params:
      - name: name
        value: docker-build-multi-platform-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-multi-platform-oci-ta@sha256:d13d7410f04a7d7ec946d1536f89d88f9f70924e2b4c41e8926f7deb8384c322
      - name: kind
        value: pipeline
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: workspace-arm64
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: workspace-s390x
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: workspace-ppc64le
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
