{
 "title": "Multiarch Tuning Operator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "custom_rate_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "prometheus_datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace='openshift-multiarch-tuning-operator', container=\"\"}) BY (pod, container, namespace)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace='openshift-multiarch-tuning-operator'}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods processing time (50th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(mto_ppo_ctrl_time_to_process_gated_pod_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "Time to process gated pods"
    },
    {},
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(mto_ppo_ctrl_time_to_process_pod_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "Pods Proc. Time"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(mto_ppo_ctrl_time_to_inspect_image_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "Single Image Inspection Time"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(mto_ppo_ctrl_time_to_inspect_pod_images_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "Pods Inspection Time"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(scheduler_framework_extension_point_duration_seconds_bucket{extension_point='PreEnqueue'}[$custom_rate_interval])))\n",
     "legendFormat": "Pods in PreEnqueue scheduler extension point "
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(scheduler_pod_scheduling_sli_duration_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "Time to schedule a pod"
    }
   ]
  },
  {
   "title": "Scheduler queues",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(scheduler_pending_pods) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(mto_ppo_wh_pods_processed_total)",
     "legendFormat": "Webhook Pods Total"
    },
    {
     "expr": "sum(mto_ppo_wh_pods_gated_total)",
     "legendFormat": "Webhook gated pods"
    },
    {
     "expr": "sum(mto_ppo_ctrl_processed_pods_total)",
     "legendFormat": "Ctrl Gated Pods"
    },
    {
     "expr": "sum(mto_ppo_ctrl_failed_image_inspection_total)",
     "legendFormat": "Inspection failures (pods)"
    },
    { "expr": "sum(mto_ppo_pods_gated)", "legendFormat": "MTO gated pods" },
    {
     "expr": "sum(scheduler_pending_pods{queue=\"gated\"})",
     "legendFormat": "Gated pods"
    },
    {}
   ]
  },
  {
   "title": "Distribution of time to inspect images",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(le) (rate(mto_ppo_ctrl_time_to_inspect_pod_images_seconds_bucket[$custom_rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of time to process gated pods",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by(le) (rate(mto_ppo_ctrl_time_to_process_gated_pod_seconds_bucket[$custom_rate_interval]))",
     "legendFormat": "{{label_name}} (2)"
    }
   ]
  },
  {
   "title": "Time to inspect pods images",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by(le) (rate(mto_ppo_ctrl_time_to_inspect_pod_images_seconds_bucket[$custom_rate_interval]))",
     "legendFormat": "Time To process Gated Pods"
    }
   ]
  },
  {
   "title": "Time to process gated pods",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by(le) (rate(mto_ppo_ctrl_time_to_process_gated_pod_seconds_bucket[$custom_rate_interval]))",
     "legendFormat": "Time To process Gated Pods"
    }
   ]
  },
  {
   "title": "Web Hook processing times",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (le) (rate(mto_ppo_wh_response_time_seconds_bucket[$custom_rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed pods (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum(rate(mto_ppo_ctrl_processed_pods_total[$custom_rate_interval]))",
     "legendFormat": "PPC Processed Gated Pods (rate)"
    },
    {
     "expr": "sum(rate(mto_ppo_ctrl_failed_image_inspection_total[$custom_rate_interval]))",
     "legendFormat": "PPC Inspection Failure (rate)"
    },
    {
     "expr": "sum(rate(mto_ppo_wh_pods_gated_total[$custom_rate_interval]))",
     "legendFormat": "WH Gated Pods Rate"
    },
    {
     "expr": "sum(scheduler_pending_pods{queue=\"gated\"})",
     "legendFormat": "Scheduling gated pods (Scheduler)"
    },
    { "expr": "sum(mto_ppo_pods_gated)", "legendFormat": "Scheduling gated pods (MTO)" }
   ]
  },
  {
   "title": "Pods processing time (ctrl)",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum by (le) (rate(mto_ppo_ctrl_time_to_process_gated_pod_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "5th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(mto_ppo_ctrl_time_to_process_gated_pod_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.25, sum by (le) (rate(mto_ppo_ctrl_time_to_process_gated_pod_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "25th"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(mto_ppo_ctrl_time_to_process_gated_pod_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "75th"
    }
   ]
  },
  {
   "title": "Time to schedule",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum by (le) (rate(scheduler_pod_scheduling_sli_duration_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "5th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(scheduler_pod_scheduling_sli_duration_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.25, sum by (le) (rate(scheduler_pod_scheduling_sli_duration_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "25th"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(scheduler_pod_scheduling_sli_duration_seconds_bucket[$custom_rate_interval])))",
     "legendFormat": "75th"
    }
   ]
  }
 ]
}